### PR TITLE
Migrated null safety

### LINKED ISSUE #93: Migrate to null safety
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description
I propose this pull request to [migrate this plugin to null safety](https://dart.dev/null-safety/migration-guide) as it is the way to go now that Flutter 2 has been released.

Here are the changes I introduced:
* Update SDK dependency version to `2.12.0+`
* Run `dart migrate` on existing code to remove unsafe nulls (for the package & example)
* Add a new version (`0.2.0`) to the changelog (as [recommended](https://dart.dev/null-safety/migration-guide#package-version))

Please check everything twice!

## Testing
- [x] Tested it manually on a Android emulator 

### Related tickets
Closes #93

### CODE REVIEW

**Comment by Armoured-Door-Studio** [comment]
Has this been publicly released yet?

**Comment by GrahamDi** [comment]
Don't think so...an ETA would be appreciated.

**Comment by dukaric1991** [comment]
Any news when this will be released?

**Comment by DevarshRanpara** [comment]
Hi @GrahamDi , @dukaric1991 .
Team is working on it,
It will be relesed within this week only.
Probebly within 2 days.
Thank you for your patience.

**Comment by GrahamDi** [comment]
Any response, at all, from the package authors would be really useful.

Looks like support is poor and I will need to move to  alternative packages. Pity.

**Comment by alexshikov** [comment]
Also interested in it.

**Comment by ryzizub** [comment]
Hopefully this will be released soon 💪

**Review by DevarshRanpara — APPROVED** [review]
Looks Good To Me.

**Comment by BirjuVachhani** [comment]
This will be released by this weekend. Thanks.

**Comment by BirjuVachhani** [comment]
This is now available in [v1.0.0](https://pub.dev/packages/showcaseview/versions/1.0.0)

**Pull request merged**
