### PR TITLE
Next and Skip button

### PR DESCRIPTION
**Pull request by Abdelazeem777**
I just added the ability to skip or next button inside Showcase itself 

Giving users more options based on their needs

# Screenshots
 
Screenshot_20211016-040700
Screenshot_20211016-040707
Screenshot_20211016-040718

### CODE REVIEW

**Comment by techwithsam** [comment]
Hi, nice work you did there

Please how can I manually create the next function manually from my code? @Abdelazeem777

**Comment by techwithsam** [comment]
> Hi, nice work you did there
> 
> Please how can I manually create the next function manually from my code? @Abdelazeem777

I mean the function for going to the next showcase.
This is very urgent pls. Thanks

**Comment by osamamohammed98** [comment]
we need skip btn for all cases  in the screen like this
Screen Shot 2022-08-01 at 10 00 57 AM

**Comment by DhvanitVaghani** [comment]
Hi @Abdelazeem777  We are glad to have your contribution. Yet, we are closing this PR for now as we have another plan for this feature. Thank you !!

**Comment by Abdelazeem777** [comment]
@DhvanitVaghani
No problems and good luck 😊

**Comment by Abdelazeem777** [comment]
@techwithsam 
Sorry for not responding it was out of my control
If you still need an answer to your question then please let me know

**Comment by techwithsam** [comment]
> @techwithsam Sorry for not responding it was out of my control If you still need an answer to your question then please let me know

No need anymore, thanks 
I have created a solution for myself

**Comment by pawarn** [comment]
Is there any way I can manually add NEXT and SKIP (for all showcase) functionality using this plugin?

Has anyone achieved this type of request?

**Comment by erperejildo** [comment]
When 

> Hi @Abdelazeem777 We are glad to have your contribution. Yet, we are closing this PR for now as we have another plan for this feature. Thank you !!

so what's the plan after one year?

**Pull request closed without merging**
