### PR TITLE
#87 - Enh - Barrier/Overlay disable interaction facilitation.

### LINKED ISSUE #87: Cannot disable when user click outside showcase
Hi, i want to disable when user click outside showcase. Because i have a logic when user click next on showcase widget(my custom). So when user click outside showcase, my logic not working and the showcase finished.

1. Showcase came out
2. I created next button to go to next showcase
3. When click outside showcase, it will to the next showcase. But my logic not working.

I expected i can disable user when click outside showcase, so it will be one access for go to next showcase with my button.

### PR DESCRIPTION
**Pull request by nvshah**
Enhancement - changes to fix #87
idea :- disable interaction with barrier/overlay. (Custom Requirement where toggling between showcase needs to be controlled)

changes :
 > param details ->
 name : **_disableBarrierInteraction_** 
 type   : **bool**

Example : 
```dart
 //...

 body: ShowCaseWidget(
         //...
          autoPlayLockEnable: false,
          //disable interaction with barrier/overlay
          disableBarrierInteraction: true,
        //...
   )

//...
```

### CODE REVIEW

**Comment by jgadsby** [comment]
This is working great for me - thank you!

**Comment by mikepyts** [comment]
Hello, thanks a lot, can you please merge that?

**Comment by jigarfumakiya** [comment]
Any update on this?

**Comment by jagged91** [comment]
> Any update on this?

I just used the library locally and made this change on my project directly

**Comment by corioste** [comment]
i need this

**Comment by vatsaltanna** [comment]
This feature is available in latest version after the merge of latest PR #252.

**Pull request closed without merging**
