### PR TITLE
fix: `textTheme` for `dart 3.4.0` and `flutter 3.22.0`

### PR DESCRIPTION
**Pull request by ziqq**
# Description
image

### CODE REVIEW

**Comment by Frezyx** [comment]
Hello @BirjuVachhani !
Please check this PR, we can't build our applications with new Flutter version ⚠️

**Comment by ziqq** [comment]
Hello @Frezyx, 

I fixed it, u can try it again.

**Comment by Frezyx** [comment]
@ziqq Hello bro! 
You misunderstood me, your fork works for me. 
I want ping package maintainer to merge this PR in the main package branch so that I don't use the fork.

**Comment by chandrabezzo** [comment]
Hi @ziqq you duplicatie #433

**Comment by chandrabezzo** [comment]
Please see #433 @Frezyx

**Comment by ziqq** [comment]
> Hi @ziqq you duplicatie #433 , CMIIW @aditya-css

Hi @chandrabezzo, yes it is, but i fix android config to

**Comment by chandrabezzo** [comment]
@ziqq your fix on Android doesn't need because just related on example.

**Comment by chandrabezzo** [comment]
We urgently need to fix on library issue not on example issue. The example still runnable on 3.22

**Pull request closed without merging**
