### PR TITLE
Bsd 2 to mit

### PR DESCRIPTION
**Pull request by vatsaltanna**

### CODE REVIEW

**Comment by BirjuVachhani** [comment]
You shouldn't be changing a license type like this. It is more critical as if the new License is less permissive then older code is at conflict because it was permissive before so now you cannot enforce new rules onto that!

**Comment by vatsaltanna** [comment]
We are planning to submit this library to google libraries which only accept Apache-2.0 or MIT License. And  I guess BSD-2  and MIT have a very slight difference between them.

**Comment by BirjuVachhani** [comment]
That seems to be a valid reason. However I do not know anything about Google libraries. Could you please provide some more information or link that you have?

When changing a license, we should add a notice on the readme file that indicates users that the license is changing in upcoming version. Should also list notable changes in attribution and terms of the licenses.

**Comment by vatsaltanna** [comment]
@BirjuVachhani Its https://devlibrary.withgoogle.com/

**Comment by BirjuVachhani** [comment]
LGTM

**Review by sanket-simform — APPROVED** [review]

**Pull request merged**
